[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4==4.14.2",
    "lxml==6.0.2",
    "markdown==3.9",
    "pillow==12.0.0",
    "soupsieve==2.8",
    "typing-extensions==4.15.0",
]
